apiVersion: v1
kind: Pod
metadata:
  name: volpod
spec:
  containers:
    - name: ubuntu-ctr
      image: ubuntu:latest
      command:
      - /bin/bash
      - "-c"
      - "sleep 60m"
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /data
          name: data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: pvc1
